### ISSUE TITLE
Question: compatibility

### ISSUE THREAD

**Issue by aioue** [ManuelKlaer/docker-cups-canon#1]
Where would I look to understand what printers this container might support please?

**Comment by ManuelKlaer** [comment]
CUPS natively supports all `AirPrint` and `IPP Everywhere` printers. You can find a list of these driverless printers on OpenPrinting (https://openprinting.github.io/printers/).

Running `lpinfo -m` inside the container will show a list of all supported printer models by this container. (The exact model name isn't listed, as most of these drivers are designed to work with multiple printers of the same brand).

All supported printers: [supported_printers.txt](https://github.com/user-attachments/files/17925711/supported_printers.txt)

**Comment by aioue** [comment]
Thank you very much for your help.
